-- PostgreSQL schema for the DataAgent management database.

CREATE OR REPLACE FUNCTION set_updated_time()
RETURNS TRIGGER AS $$
BEGIN
  NEW.update_time = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_updated_time_alt()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_time = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS agent (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_type VARCHAR(100) NOT NULL DEFAULT 'commonagent',
  name VARCHAR(255) NOT NULL,
  description TEXT,
  avatar TEXT,
  status VARCHAR(50) DEFAULT 'draft',
  api_key VARCHAR(255) DEFAULT NULL,
  api_key_enabled BOOLEAN DEFAULT false,
  prompt TEXT,
  category VARCHAR(100),
  admin_id BIGINT,
  tags TEXT,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS datasource (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL,
  host VARCHAR(255) NOT NULL,
  port INTEGER NOT NULL,
  database_name VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  connection_url VARCHAR(1000),
  status VARCHAR(50) DEFAULT 'inactive',
  test_status VARCHAR(50) DEFAULT 'unknown',
  description TEXT,
  creator_id BIGINT,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS business_knowledge (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_term VARCHAR(255) NOT NULL,
  description TEXT,
  synonyms TEXT,
  is_recall BOOLEAN DEFAULT true,
  agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  embedding_status VARCHAR(20) DEFAULT NULL,
  error_msg VARCHAR(255) DEFAULT NULL,
  is_deleted BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS semantic_model (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
  datasource_id INTEGER NOT NULL,
  table_name VARCHAR(255) NOT NULL,
  column_name VARCHAR(255) NOT NULL DEFAULT '',
  business_name VARCHAR(255) NOT NULL DEFAULT '',
  synonyms TEXT,
  business_description TEXT,
  column_comment VARCHAR(255) DEFAULT NULL,
  data_type VARCHAR(255) NOT NULL DEFAULT '',
  status BOOLEAN NOT NULL DEFAULT true,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_semantic_model_agent_datasource_table_column
    UNIQUE (agent_id, datasource_id, table_name, column_name)
);

CREATE TABLE IF NOT EXISTS agent_knowledge (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL,
  question TEXT,
  content TEXT,
  is_recall BOOLEAN DEFAULT true,
  embedding_status VARCHAR(20) DEFAULT NULL,
  error_msg VARCHAR(255) DEFAULT NULL,
  source_filename VARCHAR(500) DEFAULT NULL,
  file_path VARCHAR(500) DEFAULT NULL,
  file_size BIGINT DEFAULT NULL,
  file_type VARCHAR(255) DEFAULT NULL,
  splitter_type VARCHAR(50) DEFAULT 'token',
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted BOOLEAN DEFAULT false,
  is_resource_cleaned BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS logical_relation (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datasource_id INTEGER NOT NULL REFERENCES datasource(id) ON DELETE CASCADE,
  source_table_name VARCHAR(100) NOT NULL,
  source_column_name VARCHAR(100) NOT NULL,
  target_table_name VARCHAR(100) NOT NULL,
  target_column_name VARCHAR(100) NOT NULL,
  relation_type VARCHAR(20) DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  is_deleted BOOLEAN DEFAULT false,
  created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_logical_relation_unique_active_state
    UNIQUE (datasource_id, source_table_name, source_column_name, target_table_name, target_column_name, is_deleted)
);

CREATE TABLE IF NOT EXISTS agent_datasource (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
  datasource_id INTEGER NOT NULL REFERENCES datasource(id) ON DELETE CASCADE,
  is_active BOOLEAN DEFAULT false,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_agent_datasource UNIQUE (agent_id, datasource_id)
);

CREATE TABLE IF NOT EXISTS agent_preset_question (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT false,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_skill_binding (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
  skill_id VARCHAR(128) NOT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_agent_skill_binding UNIQUE (agent_id, skill_id)
);

CREATE TABLE IF NOT EXISTS chat_session (
  id VARCHAR(36) PRIMARY KEY,
  agent_id INTEGER NOT NULL REFERENCES agent(id) ON DELETE CASCADE,
  title VARCHAR(255) DEFAULT '新对话',
  status VARCHAR(50) DEFAULT 'active',
  is_pinned BOOLEAN DEFAULT false,
  user_id BIGINT,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_message (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(36) NOT NULL REFERENCES chat_session(id) ON DELETE CASCADE,
  role VARCHAR(20) NOT NULL,
  content TEXT NOT NULL,
  message_type VARCHAR(50) DEFAULT 'text',
  metadata JSONB,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent_datasource_tables (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_datasource_id INTEGER NOT NULL REFERENCES agent_datasource(id) ON UPDATE CASCADE ON DELETE CASCADE,
  table_name VARCHAR(255) NOT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_agent_ds_tables_ds_table UNIQUE (agent_datasource_id, table_name)
);

CREATE TABLE IF NOT EXISTS agent_datasource_columns (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_datasource_id INTEGER NOT NULL REFERENCES agent_datasource(id) ON UPDATE CASCADE ON DELETE CASCADE,
  table_name VARCHAR(255) NOT NULL,
  column_name VARCHAR(255) NOT NULL,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_agent_ds_cols_ds_table_col UNIQUE (agent_datasource_id, table_name, column_name)
);

CREATE TABLE IF NOT EXISTS model_config (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider VARCHAR(255) NOT NULL,
  base_url VARCHAR(255) NOT NULL,
  api_key VARCHAR(255) NOT NULL,
  model_name VARCHAR(255) NOT NULL,
  temperature NUMERIC(10,2) DEFAULT 0.00,
  is_active BOOLEAN DEFAULT false,
  max_tokens INTEGER DEFAULT 2000,
  context_window_tokens INTEGER DEFAULT 32768,
  model_type VARCHAR(20) NOT NULL DEFAULT 'CHAT',
  completions_path VARCHAR(255) DEFAULT NULL,
  embeddings_path VARCHAR(255) DEFAULT NULL,
  created_time TIMESTAMP DEFAULT NULL,
  updated_time TIMESTAMP DEFAULT NULL,
  is_deleted BOOLEAN DEFAULT false,
  proxy_enabled BOOLEAN DEFAULT false,
  proxy_host VARCHAR(255) DEFAULT NULL,
  proxy_port INTEGER DEFAULT NULL,
  proxy_username VARCHAR(255) DEFAULT NULL,
  proxy_password VARCHAR(255) DEFAULT NULL
);

CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS vector_store (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  content TEXT,
  metadata JSON,
  embedding vector(1024)
);

CREATE INDEX IF NOT EXISTS idx_agent_type ON agent(agent_type);
CREATE INDEX IF NOT EXISTS idx_agent_name ON agent(name);
CREATE INDEX IF NOT EXISTS idx_agent_status ON agent(status);
CREATE INDEX IF NOT EXISTS idx_agent_category ON agent(category);
CREATE INDEX IF NOT EXISTS idx_agent_admin_id ON agent(admin_id);
CREATE INDEX IF NOT EXISTS idx_business_term ON business_knowledge(business_term);
CREATE INDEX IF NOT EXISTS idx_business_agent_id ON business_knowledge(agent_id);
CREATE INDEX IF NOT EXISTS idx_business_is_recall ON business_knowledge(is_recall);
CREATE INDEX IF NOT EXISTS idx_business_embedding_status ON business_knowledge(embedding_status);
CREATE INDEX IF NOT EXISTS idx_business_is_deleted ON business_knowledge(is_deleted);
CREATE INDEX IF NOT EXISTS idx_semantic_agent_id ON semantic_model(agent_id);
CREATE INDEX IF NOT EXISTS idx_semantic_datasource_id ON semantic_model(datasource_id);
CREATE INDEX IF NOT EXISTS idx_semantic_business_name ON semantic_model(business_name);
CREATE INDEX IF NOT EXISTS idx_semantic_status ON semantic_model(status);
CREATE INDEX IF NOT EXISTS idx_agent_knowledge_agent_recall ON agent_knowledge(agent_id, is_recall);
CREATE INDEX IF NOT EXISTS idx_agent_knowledge_embedding_status ON agent_knowledge(embedding_status);
CREATE INDEX IF NOT EXISTS idx_agent_knowledge_is_deleted ON agent_knowledge(is_deleted);
CREATE INDEX IF NOT EXISTS idx_datasource_name ON datasource(name);
CREATE INDEX IF NOT EXISTS idx_datasource_type ON datasource(type);
CREATE INDEX IF NOT EXISTS idx_datasource_status ON datasource(status);
CREATE INDEX IF NOT EXISTS idx_datasource_creator_id ON datasource(creator_id);
CREATE INDEX IF NOT EXISTS idx_logical_relation_datasource_id ON logical_relation(datasource_id);
CREATE INDEX IF NOT EXISTS idx_logical_relation_source_table ON logical_relation(datasource_id, source_table_name);
CREATE INDEX IF NOT EXISTS idx_agent_datasource_agent_id ON agent_datasource(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_datasource_datasource_id ON agent_datasource(datasource_id);
CREATE INDEX IF NOT EXISTS idx_agent_datasource_is_active ON agent_datasource(is_active);
CREATE INDEX IF NOT EXISTS idx_agent_preset_question_agent_id ON agent_preset_question(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_preset_question_sort_order ON agent_preset_question(sort_order);
CREATE INDEX IF NOT EXISTS idx_agent_preset_question_is_active ON agent_preset_question(is_active);
CREATE INDEX IF NOT EXISTS idx_agent_skill_binding_skill_id ON agent_skill_binding(skill_id);
CREATE INDEX IF NOT EXISTS idx_agent_skill_binding_agent_id ON agent_skill_binding(agent_id);
CREATE INDEX IF NOT EXISTS idx_chat_session_agent_id ON chat_session(agent_id);
CREATE INDEX IF NOT EXISTS idx_chat_session_user_id ON chat_session(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_session_status ON chat_session(status);
CREATE INDEX IF NOT EXISTS idx_chat_session_is_pinned ON chat_session(is_pinned);
CREATE INDEX IF NOT EXISTS idx_chat_session_create_time ON chat_session(create_time);
CREATE INDEX IF NOT EXISTS idx_chat_message_session_id ON chat_message(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_message_role ON chat_message(role);
CREATE INDEX IF NOT EXISTS idx_chat_message_type ON chat_message(message_type);
CREATE INDEX IF NOT EXISTS idx_chat_message_create_time ON chat_message(create_time);
CREATE INDEX IF NOT EXISTS spring_ai_vector_index ON vector_store USING hnsw (embedding vector_cosine_ops);

DROP TRIGGER IF EXISTS trg_agent_update_time ON agent;
CREATE TRIGGER trg_agent_update_time BEFORE UPDATE ON agent FOR EACH ROW EXECUTE FUNCTION set_updated_time();
DROP TRIGGER IF EXISTS trg_datasource_update_time ON datasource;
CREATE TRIGGER trg_datasource_update_time BEFORE UPDATE ON datasource FOR EACH ROW EXECUTE FUNCTION set_updated_time();
DROP TRIGGER IF EXISTS trg_agent_datasource_update_time ON agent_datasource;
CREATE TRIGGER trg_agent_datasource_update_time BEFORE UPDATE ON agent_datasource FOR EACH ROW EXECUTE FUNCTION set_updated_time();
DROP TRIGGER IF EXISTS trg_agent_preset_question_update_time ON agent_preset_question;
CREATE TRIGGER trg_agent_preset_question_update_time BEFORE UPDATE ON agent_preset_question FOR EACH ROW EXECUTE FUNCTION set_updated_time();
DROP TRIGGER IF EXISTS trg_agent_skill_binding_update_time ON agent_skill_binding;
CREATE TRIGGER trg_agent_skill_binding_update_time BEFORE UPDATE ON agent_skill_binding FOR EACH ROW EXECUTE FUNCTION set_updated_time();
DROP TRIGGER IF EXISTS trg_chat_session_update_time ON chat_session;
CREATE TRIGGER trg_chat_session_update_time BEFORE UPDATE ON chat_session FOR EACH ROW EXECUTE FUNCTION set_updated_time();
DROP TRIGGER IF EXISTS trg_agent_datasource_tables_update_time ON agent_datasource_tables;
CREATE TRIGGER trg_agent_datasource_tables_update_time BEFORE UPDATE ON agent_datasource_tables FOR EACH ROW EXECUTE FUNCTION set_updated_time();
DROP TRIGGER IF EXISTS trg_agent_datasource_columns_update_time ON agent_datasource_columns;
CREATE TRIGGER trg_agent_datasource_columns_update_time BEFORE UPDATE ON agent_datasource_columns FOR EACH ROW EXECUTE FUNCTION set_updated_time();

DROP TRIGGER IF EXISTS trg_business_knowledge_updated_time ON business_knowledge;
CREATE TRIGGER trg_business_knowledge_updated_time BEFORE UPDATE ON business_knowledge FOR EACH ROW EXECUTE FUNCTION set_updated_time_alt();
DROP TRIGGER IF EXISTS trg_semantic_model_updated_time ON semantic_model;
CREATE TRIGGER trg_semantic_model_updated_time BEFORE UPDATE ON semantic_model FOR EACH ROW EXECUTE FUNCTION set_updated_time_alt();
DROP TRIGGER IF EXISTS trg_agent_knowledge_updated_time ON agent_knowledge;
CREATE TRIGGER trg_agent_knowledge_updated_time BEFORE UPDATE ON agent_knowledge FOR EACH ROW EXECUTE FUNCTION set_updated_time_alt();
DROP TRIGGER IF EXISTS trg_logical_relation_updated_time ON logical_relation;
CREATE TRIGGER trg_logical_relation_updated_time BEFORE UPDATE ON logical_relation FOR EACH ROW EXECUTE FUNCTION set_updated_time_alt();
DROP TRIGGER IF EXISTS trg_model_config_updated_time ON model_config;
CREATE TRIGGER trg_model_config_updated_time BEFORE UPDATE ON model_config FOR EACH ROW EXECUTE FUNCTION set_updated_time_alt();
